version: "3.9"

services:
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile.dev
    working_dir: /app
    command: pnpm dev -p 3000
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - WATCHPACK_INTERVAL=1000 
    volumes:
      - ./apps/web:/app
      - web_node_modules:/app/node_modules
      - web_next:/app/.next
    depends_on:
      - api

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile.dev
    working_dir: /app
    command: sh -c "pnpm prisma generate && pnpm start:dev"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
      - CHOKIDAR_INTERVAL=1000
      - WATCHPACK_POLLING=true 
    volumes:
      - ./apps/api:/app
      - ./apps/api/prisma:/app/prisma
      - api_node_modules:/app/node_modules

volumes:
  web_node_modules:
  web_next:
  api_node_modules:
